apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        #image: ${DOCKERHUB_USERNAME}/node-remote-test:latest #ถ้าเชื่อมกับ DockerHub ใช้ตัวนี้แทน
        image: gwangyasation/node-remote-test:latest # เปลี่ยนเป็นชื่อ image ของคุณ
        ports:
        - containerPort: 3000
