# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer  # เปลี่ยนจาก LoadBalancer เป็น ClusterIP
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80         # พอร์ตที่ Service รับจาก Ingress
      targetPort: 3000 # พอร์ตที่แอปใน Container รันอยู่
